services:

  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d

  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - '9906:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_mvc

volumes:
  mysql_data:
    name: mvc_mysql_data
